### PR TITLE
Test

### PR DESCRIPTION
**Pull request by idea360**

### CODE REVIEW

**Comment by idea360** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **idea360**

If they are not already assigned, you can assign the PR to them by writing `/assign @idea360` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/idea360/jx-demo/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by idea360** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/idea360/jx-demo/pull/3#issuecomment-435958742" title="LGTM">gb-ckedzierski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **idea360**

If they are not already assigned, you can assign the PR to them by writing `/assign @idea360` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/idea360/jx-demo/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by idea360** [comment]
@gb-ckedzierski: changing LGTM is restricted to assignees, and only idea360/jx-demo repo collaborators may be assigned issues.

<details>

In response to [this](https://github.com/idea360/jx-demo/pull/3#issuecomment-435958742):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gb-ckedzierski** [comment]
assign @idea360

**Comment by idea360** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/idea360/jx-demo/pull/3#issuecomment-435959100" title="Approved">gb-ckedzierski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **idea360**

If they are not already assigned, you can assign the PR to them by writing `/assign @idea360` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/idea360/jx-demo/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by idea360** [comment]
@idea360: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/idea360/jx-demo/pull/3#issuecomment-435959653):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by idea360** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/idea360/jx-demo/pull/3#pullrequestreview-171673916" title="Approved">gb-ckedzierski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **idea360**

If they are not already assigned, you can assign the PR to them by writing `/assign @idea360` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/idea360/jx-demo/blob//OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by idea360** [comment]
@gb-ckedzierski: GitHub didn't allow me to assign the following users: gb-ckedzierski.

Note that only [idea360 members](https://github.com/orgs/idea360/people) and repo collaborators can be assigned. 
For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/#issue-assignment-in-github)

<details>

In response to [this](https://github.com/idea360/jx-demo/pull/3#issuecomment-435965131):

>/assign @gb-ckedzierski 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by idea360** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/idea360/jx-demo/pull/3#issuecomment-435966427" title="LGTM">gb-ckedzierski</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/idea360/jx-demo/blob/master/OWNERS)~~ [gb-ckedzierski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
